use ass1;
SELECT DEPT_CODE, MIN(BASIC), MAX(BASIC), AVG(BASIC) FROM EMPLOYEE GROUP BY DEPT_CODE;

SELECT DEPT_CODE , COUNT(*) FROM EMPLOYEE WHERE SEX = 'F' GROUP BY DEPT_CODE; 

SELECT DEPT_CODE, CITY, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_CODE, CITY;

SELECT DESIG_CODE , COUNT(*) FROM EMPLOYEE WHERE SUBSTR(JN_DT,3,2) = '20' GROUP BY DESIG_CODE ORDER BY COUNT(*);

SELECT DEPT_CODE , SUM(BASIC) AS TOTAL_BASIC FROM EMPLOYEE WHERE SEX = 'M' GROUP BY DEPT_CODE HAVING SUM(BASIC) > 50000 ORDER BY SUM(BASIC) DESC;

SELECT e.EMP_NAME, d.DESIG_DESC , e.BASIC FROM EMPLOYEE e, DESIGNATION d  WHERE e.DESIG_CODE = d.DESIG_CODE;

SELECT e.EMP_NAME, d.DESIG_DESC, dp.DEPT_NAME, e.BASIC FROM EMPLOYEE e, DESIGNATION d, DEPARTMENT dp WHERE e.DESIG_CODE = d.DESIG_CODE AND e.DEPT_CODE = dp.DEPT_CODE;

SELECT DEPT_CODE FROM DEPARTMENT WHERE DEPT_CODE NOT IN (SELECT DEPT_CODE FROM EMPLOYEE);

SELECT DEPT_NAME FROM DEPARTMENT WHERE DEPT_CODE IN	(SELECT DEPT_CODE FROM EMPLOYEE);

INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E115', 'Meghashri Saha', 'PR', 'OFF', 'F', 'New P.O. Road', 'Pune', 'Maharashtra', '421345',70000,DATE '2020-04-03');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE,DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT)
VALUES('E116', 'Priyanka Roy', 'MN','F', 'Pali Hill', 'Mumbai','Maharashtra', '400025', 65000, DATE '2019-09-02'); 
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E117', 'Sudip Ghosh', 'PR', 'OFF', 'M', 'Ashutosh Mukherjee ROad', 'Kolkata', 'West Bengal', '700020',65000, DATE '2019-02-09');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E118', 'Arijit Maity', 'PR', 'EXE', 'M', '20B Narkeldanga', 'Kolkata','West Bengal', '711097', 45000, DATE '2020-07-03');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E119', 'Sneha Das', 'PR', 'CL', 'F', '5 Canning Street', 'Jalpaiguri', 'West Bengal', '723098', 35000, DATE '2021-08-03');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E120', 'Imanur Rahaman', 'PR', 'OFF', 'M', '128 Danesh Shekh Lane', 'Howrah', 'West Bengal', '711204', 70000, DATE '2019-10-09');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E121', 'Riya Parvin', 'PR', 'MN', 'F', 'Pune Lavasa Campus', 'Pune', 'Maharashtra', '400087', 65000, DATE '2020-09-03');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E122', 'Reshmi Kundu', 'PR', 'Cl', 'F', 'Lajpat Nagar', 'Delhi', 'Delhi','100087', 25000, DATE '2021-07-03');
INSERT INTO EMPLOYEE(EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES ('E123', 'Manshi Shaw', 'PR', 'EXE', 'F', 'IT Building,Yojana Bhawan', 'Jaipur', 'Rajasthan', '302005',50000, DATE '2019-08-06'); 

SELECT d.DEPT_NAME FROM DEPARTMENT d  WHERE (SELECT COUNT(*) FROM EMPLOYEE e WHERE e.DEPT_CODE = d.DEPT_CODE) > 9;

SELECT DEPT_CODE, BASIC AS MAX_BASIC FROM EMPLOYEE WHERE BASIC = (SELECT MAX(BASIC) FROM EMPLOYEE);

SELECT d.DESIG_DESC , e.BASIC AS MAX_BASIC FROM EMPLOYEE e, DESIGNATION d WHERE e.DESIG_CODE = d.DESIG_CODE	AND e.BASIC = (SELECT MAX(BASIC) FROM EMPLOYEE);

SELECT d.DEPT_NAME, COUNT(*) AS NO_OF_MANAGER FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE AND e.DESIG_CODE = 
(SELECT DESIG_CODE FROM DESIGNATION WHERE DESIG_DESC = 'Manager') GROUP BY d.DEPT_NAME;


 SELECT d.DEPT_NAME, e.BASIC FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE AND e.BASIC >= ALL(SELECT BASIC FROM EMPLOYEE);
 
 SELECT DISTINCT BASIC AS MIN_BASIC FROM EMPLOYEE e WHERE e.BASIC <= ALL(SELECT BASIC FROM EMPLOYEE); 
 
SELECT d.DEPT_NAME, e.BASIC FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE AND e.BASIC >= ALL(SELECT BASIC FROM EMPLOYEE);

SELECT DEPT_NAME, BASIC AS AVERAGE_BASIC FROM (SELECT DEPT_NAME , AVG(BASIC) AS BASIC FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE GROUP BY DEPT_NAME) 
WHERE BASIC = (SELECT MAX(BASIC) FROM (SELECT DEPT_NAME, AVG(BASIC) AS BASIC FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE GROUP BY DEPT_NAME)); 

SELECT DEPT_NAME, EMP_NO AS MAXIMUM_NO_OF_EMPLOYEE FROM
(SELECT DEPT_NAME, COUNT(EMP_CODE) AS EMP_NO FROM EMPLOYEE e DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE GROUP BY DEPT_NAME)
 WHERE EMP_NO = (SELECT MAX(EMP_NO) FROM EMPLOYEE e, DEPARTMENT dWHERE e.DEPT_CODE = d.DEPT_CODE GROUP BY DEPT_NAME));


INSERT INTO EMPLOYEE(EMP_CODE,EMP_NAME, DEPT_CODE, DESIG_CODE, SEX,ADDRESS, CITY, STATE, PIN, BASIC, JN_DT) 
VALUES('E24','Sarthak dubey', 'PUR', 'SALES', 'M', '45B Gariahat Road', 'Kolkata', 'West Bengal','700034',45000,DATE '2019-02-01');
INSERT INTO EMPLOYEE(EMP_CODE,EMP_NAME, DEPT_CODE, DESIG_CODE,SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT)
VALUES ('E125','Saheli Das', 'PER', 'SALES', 'F', 'Budhdha Marg', 'Patna', 'Bihar', '600078',30000, DATE '2020-08-13');
INSERT INTO EMPLOYEE(EMP_CODE,EMP_NAME, DEPT_CODE, DESIG_CODE,SEX, ADDRESS, CITY, STATE, PIN, BASIC, JN_DT)
VALUES ('E126', 'Kastury Ganguli', 'OFF', 'REPRESENTATIVE', 'F', 'Panjiyan Bhawan','Kota', 'Rajasthan', '305001', 45000,DATE '2019-08-10'); 

DELETE FROM EMPLOYEE WHERE DESIG_CODE NOT IN (SELECT DESIG_CODE FROM DESIGNATION); 
-- 3 row(s) affected

SELECT e.EMP_NAME, e.BASIC FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE AND BASIC > (SELECT AVG(BASIC) 
FROM EMPLOYEE e, DEPARTMENT d WHERE e.DEPT_CODE = d.DEPT_CODE AND e.SEX = 'F') AND e.SEX = 'F';

SELECT COUNT(*) AS NO_OF_FEMALE_MANAGER FROM EMPLOYEE e, DESIGNATION d WHERE e.DESIG_CODE = d.DESIG_CODE AND e.SEX = 'F' AND d.DESIG_CODE = 'MN';

UPDATE EMPLOYEE SET SEX='F' WHERE EMP_CODE ='E121';
SELECT * FROM EMPLOYEE;
