USE ASS4;
CREATE TABLE EMP(
ECODE char(10) PRIMARY KEY, 
ENAME char(30), 
DCODE char(10), 
GRADE char(1), 
BASIC numeric, 
JN_DT DATE); 
-- 0 row(s) affected
INSERT INTO EMP VALUES('E1', 'Priya', 'D2', 'B', 5000, '2020-01-01'); 
INSERT INTO EMP VALUES('E2', 'Manish', 'D1', 'C', 5500, '2020-03-01'); 
INSERT INTO EMP VALUES('E3', 'Akash', 'D2', 'B', 5500, '2020-05-01'); 
INSERT INTO EMP VALUES('E4', 'Rachna', 'D4', 'A', 7000, '2019-04-06'); 
INSERT INTO EMP VALUES('E5', 'Rachna', 'D3', 'B', 7500, '2019-08-01'); 
INSERT INTO EMP VALUES('E6', 'Ritu', 'D4', 'C', 6000, '2019-12-05'); 
INSERT INTO EMP VALUES('E7', 'Aritra', 'D3', 'A',8000, '2021-02-01'); 
INSERT INTO EMP VALUES('E8', 'Piyush', 'D2', 'C', 7500, '2021-10-10'); 
INSERT INTO EMP VALUES('E9', 'Navin', 'D1', 'B', 6800, '2020-05-15'); 
INSERT INTO EMP VALUES('E10', 'Pritha', 'D4', 'A', 8500, '2019-06-12');
-- 1 row(s) affected

ALTER TABLE EMP RENAME COLUMN ECODE  TO EMPLOYEE_CODE; 
ALTER TABLE EMP RENAME COLUMN ENAME  TO NAME; 
ALTER TABLE EMP RENAME COLUMN DCODE  TO DEPT_CODE; 
ALTER TABLE EMP RENAME COLUMN JN_DT  TO JOINING_DATE; 
-- 0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0

SELECT * FROM EMP; 
-- 10 row(s) returned

SELECT FORMAT (99,999); 
COLUMN GRADE FORMAT A5; 
ALTER SESSION SET NLS_DATE_FORMAT = 'MONTH DD,YYYY'; 
SELECT DATE_FORMAT(JOINING_DATE,'%M %d,%Y') FROM EMP;
UPDATE EMP SET JOINING_DATE = DATE_FORMAT(JOINING_DATE,'%M %d, %Y');

COLUMN; 
COLUMN GRADE ON 
FORMAT A5 
COLUMN BASIC ON 
FORMAT 99,999 
6
COLUMN JN_DT ON 
HEADING 'JOINING DATE' 
COLUMN DCODE ON 
HEADING 'DEPT_CODE' 
COLUMN ENAME ON 
HEADING 'NAME' 
COLUMN ECODE ON 
HEADING 'EMPLOYEE_CODE' 
COLUMN result_plus_xquery ON 
HEADING 'Result Sequence' 
COLUMN other_plus_exp ON 
FORMAT a44 
COLUMN other_tag_plus_exp ON 
FORMAT a29 
COLUMN object_node_plus_exp ON 
FORMAT a8 
COLUMN plan_plus_exp ON 
FORMAT a60 
COLUMN parent_id_plus_exp ON 
HEADING 'p' 
FORMAT 990 
7
COLUMN id_plus_exp ON 
HEADING 'i' 
FORMAT 990 
COLUMN droptime_plus_show_recyc ON 
HEADING 'DROP TIME' 
FORMAT a19 
COLUMN objtype_plus_show_recyc ON 
HEADING 'OBJECT TYPE' 
FORMAT a12 
COLUMN objectname_plus_show_recyc ON 
HEADING 'RECYCLEBIN NAME' 
8
FORMAT a30 
COLUMN origname_plus_show_recyc ON 
HEADING 'ORIGINAL NAME' 
FORMAT a16 
COLUMN value_col_plus_show_param ON 
HEADING 'VALUE' 
FORMAT a30 
COLUMN name_col_plus_show_param ON 
HEADING 'NAME' 
FORMAT a36 
COLUMN units_col_plus_show_sga ON 
FORMAT a15 
COLUMN name_col_plus_show_sga ON 
FORMAT a24 
COLUMN ERROR ON FORMAT 
A65 word_wrap 
COLUMN LINE/COL ON 
FORMAT A8 
COLUMN ROWLABEL ON 
FORMAT A15 
