CREATE TABLE EMP(
ECODE char(10) PRIMARY KEY, 
ENAME char(30), 
DCODE char(10), 
GRADE char(1), 
BASIC number, 
JN_DT DATE); 

INSERT INTO EMP VALUES('E1', 'Priya', 'D2', 'B', 5000, '02-JAN2020'); 
INSERT INTO EMP VALUES('E2', 'Manish', 'D1', 'C', 5500, '01-MAR2020'); 
INSERT INTO EMP VALUES('E3', 'Akash', 'D2', 'B', 5500, '01-MAY2020'); 
INSERT INTO EMP VALUES('E4', 'Rachna', 'D4', 'A', 7000, '06-APR2019'); 
INSERT INTO EMP VALUES('E5', 'Rachna', 'D3', 'B', 7500, '01-AUG2019'); 
INSERT INTO EMP VALUES('E6', 'Ritu', 'D4', 'C', 6000, '05-DEC2019'); 
INSERT INTO EMP VALUES('E7', 'Aritra', 'D3', 'A',8000, '01-FEB2021'); 
INSERT INTO EMP VALUES('E8', 'Piyush', 'D2', 'C', 7500, '10-OCT2021'); 
INSERT INTO EMP VALUES('E9', 'Navin', 'D1', 'B', 6800, '15-MAY2020'); 
INSERT INTO EMP VALUES('E10', 'Pritha', 'D4', 'A', 8500, '12-NOV2019');

COLUMN ECODE HEADING 'EMPLOYEE_CODE'; 
COLUMN ENAME HEADING 'NAME'; 
COLUMN DCODE HEADING 'DEPT_CODE'; 
COLUMN JN_DT HEADING 'JOINING DATE'; 
SELECT * FROM EMP;

COLUMN BASIC FORMAT '99,999'; 
COLUMN GRADE FORMAT A5; 
ALTER SESSION SET NLS_DATE_FORMAT = 'MONTH DD,YYYY';
 SELECT * FROM EMP; 
COLUMN; 
COLUMN GRADE ON FORMAT A5 
COLUMN BASIC ON FORMAT 99,999 
COLUMN JN_DT ON HEADING 'JOINING DATE' 
COLUMN DCODE ON HEADING 'DEPT_CODE' 
COLUMN ENAME ON HEADING 'NAME' 
COLUMN ECODE ON HEADING 'EMPLOYEE_CODE' 
COLUMN result_plus_xquery ON HEADING 'Result Sequence' 
COLUMN other_plus_exp ON FORMAT a44 
COLUMN other_tag_plus_exp ON FORMAT a29 
COLUMN object_node_plus_exp ON FORMAT a8 
COLUMN plan_plus_exp ON FORMAT a60 
COLUMN parent_id_plus_exp ON HEADING 'p' FORMAT 990 
COLUMN id_plus_exp ON HEADING 'i' FORMAT 990 
COLUMN droptime_plus_show_recyc ON HEADING 'DROP TIME' FORMAT a19 
COLUMN objtype_plus_show_recyc ON HEADING 'OBJECT TYPE' FORMAT a12 
COLUMN objectname_plus_show_recyc ON HEADING 'RECYCLEBIN NAME' FORMAT a30 
COLUMN origname_plus_show_recyc ON HEADING 'ORIGINAL NAME' FORMAT a16 
COLUMN value_col_plus_show_param ON HEADING 'VALUE' FORMAT a30 
COLUMN name_col_plus_show_param ON HEADING 'NAME' FORMAT a36 
COLUMN units_col_plus_show_sga ON FORMAT a15 
COLUMN name_col_plus_show_sga ON FORMAT a24 
COLUMN ERROR ON FORMAT A65 word_wrap 
COLUMN LINE/COL ON FORMAT A8 
COLUMN ROWLABEL ON FORMAT A15 

COLUMN JN_DT; 
COLUMN JN_DT ON HEADING 'JOINING DATE'

 COLUMN JN_DT OFF;
 SELECT * FROM EMP;
 
COLUMN JN_DT CLEAR; 
SELECT * FROM EMP; 

CLEAR COLUMN;
SELECT * FROM EMP;
COLUMN;

 BREAK ON DCODE;
SELECT * FROM EMP ORDER BY DCODE ASC;

 BREAK ON DCODE SKIP 1;
 SELECT * FROM EMP ORDER BY DCODE ASC;
 
BREAK ON DCODE SKIP 1 ON GRADE; 
 SELECT * FROM EMP ORDER BY DCODE ASC, GRADE ASC;
 
 COLUMN GRADE FORMAT A20; 
 BREAK ON DCODE SKIP 1 ON GRADE SKIP 1; 
 COMPUTE AVG LABEL 'AVG BASIC ON GRADE' OF BASIC ON GRADE; 
 SELECT * FROM EMP ORDER BY DCODE ASC, GRADE ASC;
 
 BREAK ON REPORT SKIP 3 ON DCODE SKIP 3 ON GRADE SKIP 1; 
COMPUTE AVG LABEL 'AVG BASIC ON GRADE' OF BASIC ON GRADE; 
COMPUTE AVG LABEL "AVG BASIC ON DEPT" SUM LABEL "TOTAL BASIC ON DEPT" OF BASIC ON DCODE; 
COMPUTE AVG LABEL "AVG BASIC" SUM LABEL "TOTAL BASIC" OF BASIC ON REPORT; 
SELECT * FROM EMP ORDER BY DCODE ASC, GRADE ASC; 